apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 20000
        - containerPort: 20001
        - containerPort: 20002
        - containerPort: 20003
        env:
          - name: NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  ports:
    - port: 20
      name: ftp-data
    - port: 21
      name: ftp-connection
    - port: 20000
      name: ftps-pasv1
    - port: 20001
      name: ftps-pasv2
    - port: 20002
      name: ftps-pasv3
    - port: 20003
      name: ftps-pasv4
